"""
Ball-Bot Auto-Tuning Inner PID (Balancing Only)

This script runs a single-layer balancing controller and automatically tunes the
inner PID gains for pitch (x) and roll (y) using a relay (Åström–Hägglund)
method to estimate ultimate gain Ku and period Pu, then applies Ziegler–Nichols
PID rules.

Key changes vs cascaded controller:
- Removed steering (yaw) control
- Removed outer position/velocity loop
- Added automatic tuning routine for inner PID on startup

Safety notes:
- Auto-tuning excites small oscillations around upright; ensure you have a
  safety tether/spotter and space around the robot.
- The routine clamps angles and output; it aborts if the robot leans too far.

Author: Auto-generated by Copilot
Date: 2025-11-14
"""

import time
import json
import lcm
import threading
import numpy as np
import sys
import os
from mbot_lcm_msgs.mbot_motor_pwm_t import mbot_motor_pwm_t
from mbot_lcm_msgs.mbot_balbot_feedback_t import mbot_balbot_feedback_t

# Make both layouts work (utils/ or local files)
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))
try:
    from utils.DataLogger import dataLogger  # type: ignore
    from utils.ps4_controller_api import PS4InputHandler  # type: ignore
except Exception:
    from DataLogger import dataLogger  # type: ignore
    from ps4_controller_api import PS4InputHandler  # type: ignore

# =============================================================================
# SYSTEM CONSTANTS
# =============================================================================

FREQ = 200           # Main loop frequency [Hz]
DT = 1 / FREQ

PWM_MAX = 1.0
PWM_MIN = -1.0

N_GEARBOX = 70
N_ENC = 64
R_W = 0.048
R_K = 0.121

THETA_MAX = np.radians(6.0)  # Absolute safety limit for lean [rad]
IMU_DEADZONE = np.radians(0.5)

# =============================================================================
# GLOBALS FOR LCM
# =============================================================================

listening = False
msg = mbot_balbot_feedback_t()
last_time = 0
last_seen = {"MBOT_BALBOT_FEEDBACK": 0}


# =============================================================================
# LCM CALLBACK AND LISTENER
# =============================================================================

def feedback_handler(channel, data):
    global msg, last_seen, last_time
    last_time = time.time()
    last_seen[channel] = time.time()
    msg = mbot_balbot_feedback_t.decode(data)


def lcm_listener(lc):
    global listening, last_time, last_seen
    while listening:
        try:
            lc.handle_timeout(100)
            if time.time() - last_time > 2.0:
                print("WARNING: LCM Publisher seems inactive...")
            elif time.time() - last_seen["MBOT_BALBOT_FEEDBACK"] > 2.0:
                print("WARNING: MBOT_BALBOT_FEEDBACK node seems inactive...")
        except Exception as e:
            print(f"ERROR: LCM listening error: {e}")
            break


# =============================================================================
# UTILS
# =============================================================================

def calc_enc2rad(ticks):
    return ticks / (N_GEARBOX * N_ENC) * 2 * np.pi


def calc_kinematic_conv(psi1, psi2, psi3):
    phix = (R_W / R_K) * np.sqrt(2/3) * (psi2 - psi3)
    phiy = (R_W / R_K) * np.sqrt(2)/3 * (-2*psi1 + psi2 + psi3)
    phiz = (R_W / R_K) * np.sqrt(2)/3 * (psi1 + psi2 + psi3)
    return phix, phiy, phiz


def calc_torque_conv(Tx, Ty, Tz):
    u1 = (1/3) * (Tz - (1/np.cos(np.pi/4)) * (2*Ty))
    u2 = (1/3) * (Tz + (1/np.cos(np.pi/4)) * (-np.sqrt(3)*Tx + Ty))
    u3 = (1/3) * (Tz + (1/np.cos(np.pi/4)) * (np.sqrt(3)*Tx + Ty))
    return u1, u2, u3


def func_clip(x, lo, hi):
    if x > hi:
        return hi
    if x < lo:
        return lo
    return x


def apply_deadzone(x, dz):
    return 0.0 if abs(x) < dz else x


# =============================================================================
# PID CONTROLLER
# =============================================================================

class PIDController:
    def __init__(self, Kp, Ki, Kd, dt, integral_limit=None, output_limit=None):
        self.Kp = Kp
        self.Ki = Ki
        self.Kd = Kd
        self.dt = dt
        self.integral_limit = integral_limit
        self.output_limit = output_limit
        self.integral = 0.0
        self.prev_error = None

    def update(self, setpoint, measurement, derivative_measurement=None):
        error = setpoint - measurement
        p = self.Kp * error
        self.integral += error * self.dt
        if self.integral_limit is not None:
            self.integral = func_clip(self.integral, -self.integral_limit, self.integral_limit)
        i = self.Ki * self.integral
        if derivative_measurement is not None:
            d = -self.Kd * derivative_measurement
        elif self.prev_error is not None:
            d = self.Kd * (error - self.prev_error) / self.dt
        else:
            d = 0.0
        self.prev_error = error
        u = p + i + d
        if self.output_limit is not None:
            u = func_clip(u, self.output_limit[0], self.output_limit[1])
        return u

    def reset(self):
        self.integral = 0.0
        self.prev_error = None


# =============================================================================
# RELAY-BASED AUTOTUNER
# =============================================================================

class RelayAutoTuner:
    """
    Relay (on-off) autotuner for a single axis.

    Applies a relay control u = +/- h depending on sign(error). Measures the
    resulting sustained oscillation's amplitude (a) and period (Pu) from theta
    zero-crossings and peaks, then computes Ziegler–Nichols PID gains.
    """

    def __init__(self, axis_name: str, relay_amp: float, angle_limit: float, dt: float):
        self.axis_name = axis_name
        self.h = relay_amp
        self.angle_limit = angle_limit
        self.dt = dt
        # Detection state
        self.prev_theta = 0.0
        self.prev_sign = 0
        self.last_cross_time = None
        self.prev_pos_cross_time = None
        self.periods = []
        self.window_max = 0.0
        self.window_min = 0.0
        self.amp_list = []
        self.t = 0.0

    def control(self, theta: float) -> float:
        # Relay command based on sign of theta (error = 0 - theta)
        # If theta > 0 (lean +), command negative torque to pull back
        return -self.h if theta > 0 else self.h

    def update(self, theta: float, t_now: float):
        """Update oscillation measurement; call each loop.
        Returns tuple (done, Ku, Pu) when enough data is collected.
        """
        self.t = t_now
        # Safety
        if abs(theta) > self.angle_limit:
            raise RuntimeError(f"{self.axis_name} autotune aborted: |theta| too large ({np.degrees(theta):.1f} deg)")

        # Track extrema between zero crossings
        self.window_max = max(self.window_max, theta)
        self.window_min = min(self.window_min, theta)

        sign_now = 1 if theta >= 0 else -1
        crossed = (sign_now != self.prev_sign and self.prev_sign != 0)
        if crossed:
            # Zero-crossing detected
            if sign_now > 0:
                # Positive-going crossing: measure full period from previous positive crossing
                if self.prev_pos_cross_time is not None:
                    Pu = t_now - self.prev_pos_cross_time
                    self.periods.append(Pu)
                    # Amplitude a is half the peak-to-peak in last half-cycle window
                    a = 0.5 * (self.window_max - self.window_min)
                    if a > 1e-6:
                        self.amp_list.append(a)
                self.prev_pos_cross_time = t_now
            # Reset window for next half-cycle
            self.window_max = -1e9
            self.window_min = 1e9

        self.prev_sign = sign_now

        # Decide completion: need at least 2-3 stable periods
        if len(self.periods) >= 3 and len(self.amp_list) >= 3:
            Pu_avg = float(np.median(self.periods[-3:]))
            a_avg = float(np.median(self.amp_list[-3:]))
            # Basic sanity: recent variation small
            Pu_var = np.std(self.periods[-3:]) / Pu_avg if Pu_avg > 0 else 1.0
            a_var = np.std(self.amp_list[-3:]) / a_avg if a_avg > 0 else 1.0
            if Pu_var < 0.15 and a_var < 0.15:
                Ku = 4 * self.h / (np.pi * a_avg)
                return True, Ku, Pu_avg
        return False, None, None


# =============================================================================
# MAIN
# =============================================================================

def main():
    # Data logging
    trial_num = int(input("Test Number? "))
    filename = f"ballbot_control_{trial_num}.txt"
    dl = dataLogger(filename)
    print(f"Data will be saved to: {filename}")

    # LCM setup
    global listening, msg
    lc = lcm.LCM("udpm://239.255.76.67:7667?ttl=0")
    subscription = lc.subscribe("MBOT_BALBOT_FEEDBACK", feedback_handler)
    listening = True
    listener_thread = threading.Thread(target=lcm_listener, args=(lc,), daemon=True)
    listener_thread.start()
    print("✓ LCM listener started")

    # Controller input (still allow R1 to reset IMU; joysticks ignored)
    controller = PS4InputHandler(interface="/dev/input/js0", connecting_using_ds4drv=False)
    controller_thread = threading.Thread(target=controller.listen, args=(10,))
    controller_thread.daemon = True
    controller_thread.start()
    print("✓ PS4 Controller initialized")

    # Inner PID placeholders (gains will be auto-tuned)
    inner_pid_x = PIDController(Kp=6.0, Ki=0.0, Kd=0.5, dt=DT, integral_limit=0.5, output_limit=(-PWM_MAX, PWM_MAX))
    inner_pid_y = PIDController(Kp=6.0, Ki=0.0, Kd=0.5, dt=DT, integral_limit=0.5, output_limit=(-PWM_MAX, PWM_MAX))

    print("\nStarting control loop in 0.5 seconds...")
    time.sleep(0.5)

    # Data header
    data_header = [
        "i", "t_now",
        "Tx", "Ty",
        "u1", "u2", "u3",
        "theta_x", "theta_y", "theta_z",
        "psi_1", "psi_2", "psi_3",
        "phi_x", "phi_y",
        "x", "y",
        "dx", "dy",
        "state", "Kp_x", "Ki_x", "Kd_x", "Kp_y", "Ki_y", "Kd_y"
    ]
    dl.appendData([" ".join(data_header)])

    # Command message
    command = mbot_motor_pwm_t()

    # Initial references
    enc_pos_1_start = msg.enc_ticks[0]
    enc_pos_2_start = msg.enc_ticks[1]
    enc_pos_3_start = msg.enc_ticks[2]

    theta_x_0 = msg.imu_angles_rpy[0]
    theta_y_0 = msg.imu_angles_rpy[1]
    theta_z_0 = msg.imu_angles_rpy[2]

    # State machine
    STATE_TUNE_X = 0
    STATE_TUNE_Y = 1
    STATE_BALANCE = 2
    state = STATE_TUNE_X

    # Autotuners
    RELAY_AMP = 0.18  # PWM fraction for relay amplitude (tweak if needed)
    SAFE_ANGLE = np.radians(4.0)  # tighter than THETA_MAX during tune
    tuner_x = RelayAutoTuner("X", relay_amp=RELAY_AMP, angle_limit=SAFE_ANGLE, dt=DT)
    tuner_y = RelayAutoTuner("Y", relay_amp=RELAY_AMP, angle_limit=SAFE_ANGLE, dt=DT)

    # Loop vars
    i = 0
    t_start = time.time()
    prev_x = prev_y = 0.0

    try:
        while True:
            time.sleep(DT)
            t_now = time.time() - t_start
            i += 1

            # Read sensors
            theta_x_raw = msg.imu_angles_rpy[0] - theta_x_0
            theta_y_raw = msg.imu_angles_rpy[1] - theta_y_0
            theta_z_raw = msg.imu_angles_rpy[2] - theta_z_0

            theta_x = apply_deadzone(theta_x_raw, IMU_DEADZONE)
            theta_y = apply_deadzone(theta_y_raw, IMU_DEADZONE)
            theta_z = apply_deadzone(theta_z_raw, IMU_DEADZONE)

            # Encoders
            enc_pos_1 = msg.enc_ticks[0] - enc_pos_1_start
            enc_pos_2 = msg.enc_ticks[1] - enc_pos_2_start
            enc_pos_3 = msg.enc_ticks[2] - enc_pos_3_start

            psi_1 = calc_enc2rad(enc_pos_1)
            psi_2 = calc_enc2rad(enc_pos_2)
            psi_3 = calc_enc2rad(enc_pos_3)

            phi_x, phi_y, phi_z = calc_kinematic_conv(psi_1, psi_2, psi_3)
            x = phi_x * R_K
            y = phi_y * R_K
            dx = (x - prev_x) / DT
            dy = (y - prev_y) / DT
            prev_x, prev_y = x, y

            # Inputs
            bt = controller.get_signals()
            shoulder_R1 = bt["shoulder_R1"]
            if shoulder_R1 == 1:
                theta_x_0 = msg.imu_angles_rpy[0]
                theta_y_0 = msg.imu_angles_rpy[1]
                theta_z_0 = msg.imu_angles_rpy[2]
                print("\n>>> IMU REFERENCE RESET <<<\n")

            # Control logic
            Tx = Ty = 0.0

            if state == STATE_TUNE_X:
                # Hold Y with mild damping using current PID gains (very low Kp/Kd)
                Ty = inner_pid_y.update(0.0, theta_y)
                # Relay on X
                try:
                    Tx = tuner_x.control(theta_x)
                    done, Ku, Pu = tuner_x.update(theta_x, t_now)
                    if done:
                        # Tyreus–Luyben PID (safer for oscillatory/unstable plants)
                        # References commonly use: Kp=0.454Ku, Ti=2.2Pu, Td=0.159Pu
                        Kp = 0.454 * Ku
                        Ti = 2.2 * Pu
                        Td = 0.159 * Pu
                        Ki = Kp / Ti if Ti > 1e-3 else 0.0
                        Kd = Kp * Td
                        inner_pid_x.Kp, inner_pid_x.Ki, inner_pid_x.Kd = Kp, Ki, Kd
                        inner_pid_x.reset()
                        print(f"✓ X-axis tuned (Tyreus–Luyben): Ku={Ku:.3f}, Pu={Pu:.3f} -> Kp={Kp:.3f}, Ki={Ki:.3f}, Kd={Kd:.3f}")
                        # Persist partial results
                        try:
                            gains_path = os.path.join(os.path.dirname(__file__), 'pid_gains.json')
                            payload = {
                                'inner_x': {'Kp': inner_pid_x.Kp, 'Ki': inner_pid_x.Ki, 'Kd': inner_pid_x.Kd},
                            }
                            # If file exists, merge
                            if os.path.exists(gains_path):
                                with open(gains_path, 'r') as f:
                                    try:
                                        existing = json.load(f)
                                    except Exception:
                                        existing = {}
                            else:
                                existing = {}
                            existing.update(payload)
                            with open(gains_path, 'w') as f:
                                json.dump(existing, f, indent=4)
                            print(f"→ Saved X gains to {gains_path}")
                        except Exception as e:
                            print(f"WARN: Could not save X gains: {e}")
                        state = STATE_TUNE_Y
                except RuntimeError as e:
                    print(e)
                    # Abort tuning; keep conservative gains
                    state = STATE_BALANCE

            elif state == STATE_TUNE_Y:
                # Hold X with tuned PID
                Tx = inner_pid_x.update(0.0, theta_x)
                try:
                    Ty = tuner_y.control(theta_y)
                    done, Ku, Pu = tuner_y.update(theta_y, t_now)
                    if done:
                        # Tyreus–Luyben PID
                        Kp = 0.454 * Ku
                        Ti = 2.2 * Pu
                        Td = 0.159 * Pu
                        Ki = Kp / Ti if Ti > 1e-3 else 0.0
                        Kd = Kp * Td
                        inner_pid_y.Kp, inner_pid_y.Ki, inner_pid_y.Kd = Kp, Ki, Kd
                        inner_pid_y.reset()
                        print(f"✓ Y-axis tuned (Tyreus–Luyben): Ku={Ku:.3f}, Pu={Pu:.3f} -> Kp={Kp:.3f}, Ki={Ki:.3f}, Kd={Kd:.3f}")
                        # Persist results for both axes
                        try:
                            gains_path = os.path.join(os.path.dirname(__file__), 'pid_gains.json')
                            if os.path.exists(gains_path):
                                with open(gains_path, 'r') as f:
                                    try:
                                        existing = json.load(f)
                                    except Exception:
                                        existing = {}
                            else:
                                existing = {}
                            existing.update({
                                'inner_x': {'Kp': inner_pid_x.Kp, 'Ki': inner_pid_x.Ki, 'Kd': inner_pid_x.Kd},
                                'inner_y': {'Kp': inner_pid_y.Kp, 'Ki': inner_pid_y.Ki, 'Kd': inner_pid_y.Kd},
                            })
                            with open(gains_path, 'w') as f:
                                json.dump(existing, f, indent=4)
                            print(f"→ Saved X/Y gains to {gains_path}")
                        except Exception as e:
                            print(f"WARN: Could not save gains: {e}")
                        state = STATE_BALANCE
                except RuntimeError as e:
                    print(e)
                    state = STATE_BALANCE

            else:  # STATE_BALANCE
                # Use tuned inner PIDs to hold upright
                Ty = inner_pid_x.update(0.0, theta_x)
                Tx = inner_pid_y.update(0.0, theta_y)

            # Convert to motor PWMs (no yaw)
            u1, u2, u3 = calc_torque_conv(Tx, Ty, 0.0)
            u1 = func_clip(u1, PWM_MIN, PWM_MAX)
            u2 = func_clip(u2, PWM_MIN, PWM_MAX)
            u3 = func_clip(u3, PWM_MIN, PWM_MAX)

            # Publish
            command.utime = int(time.time() * 1e6)
            command.pwm[0] = u1
            command.pwm[1] = u2
            command.pwm[2] = u3
            lc.publish("MBOT_MOTOR_PWM_CMD", command.encode())

            # Log
            dl.appendData([
                i, t_now,
                Tx, Ty,
                u1, u2, u3,
                theta_x, theta_y, theta_z,
                psi_1, psi_2, psi_3,
                phi_x, phi_y,
                x, y,
                dx, dy,
                state,
                inner_pid_x.Kp, inner_pid_x.Ki, inner_pid_x.Kd,
                inner_pid_y.Kp, inner_pid_y.Ki, inner_pid_y.Kd,
            ])

            # Console every 10 cycles
            if i % 10 == 0:
                state_name = {STATE_TUNE_X: "TUNE_X", STATE_TUNE_Y: "TUNE_Y", STATE_BALANCE: "BALANCE"}[state]
                print(
                    f"[{state_name}] t={t_now:.2f}s | T=[{Tx:.2f},{Ty:.2f}] | u=[{u1:.2f},{u2:.2f},{u3:.2f}] | "
                    f"θ=[{np.degrees(theta_x):.1f}°, {np.degrees(theta_y):.1f}°]"
                )

    except KeyboardInterrupt:
        print("\n\n=== EMERGENCY STOP ===")
        command = mbot_motor_pwm_t()
        command.utime = int(time.time() * 1e6)
        command.pwm[0] = 0.0
        command.pwm[1] = 0.0
        command.pwm[2] = 0.0
        lc.publish("MBOT_MOTOR_PWM_CMD", command.encode())
    finally:
        print("\n=== SHUTDOWN ===")
        print(f"→ Saving data to {filename}...")
        dl.writeOut()
        global listening
        listening = False
        # Give threads a moment to stop
        time.sleep(0.2)
        try:
            controller.on_options_press()
        except Exception:
            pass
        # Final motor off
        command = mbot_motor_pwm_t()
        command.utime = int(time.time() * 1e6)
        command.pwm[0] = 0.0
        command.pwm[1] = 0.0
        command.pwm[2] = 0.0
        lc.publish("MBOT_MOTOR_PWM_CMD", command.encode())
        print("✓ Motors confirmed off")


if __name__ == "__main__":
    main()
