"""
Ball-Bot LQR Controller with Extended Kalman Filter

This script implements an optimal state-feedback balancing controller using:
- LQR (Linear Quadratic Regulator) for computing optimal control gains
- EKF (Extended Kalman Filter) for state estimation with noise rejection

Key features:
- No manual tuning required; gains computed from dynamics and cost matrices
- EKF fuses IMU and encoder measurements to estimate full state
- Optimal balance between performance (Q) and control effort (R)
- Removed steering (yaw) and outer position loop for simplicity

State vector x = [θx, θy, θ̇x, θ̇y, φx, φy, φ̇x, φ̇y]ᵀ
- θx, θy: pitch/roll angles [rad]
- θ̇x, θ̇y: angular velocities [rad/s]
- φx, φy: ball position angles [rad]
- φ̇x, φ̇y: ball angular velocities [rad/s]

Control input u = [Tx, Ty]ᵀ (no yaw control)

Author: Auto-generated by Copilot
Date: 2025-11-14
"""

import time
import json
import lcm
import threading
import numpy as np
import sys
import os
from scipy import linalg
from mbot_lcm_msgs.mbot_motor_pwm_t import mbot_motor_pwm_t
from mbot_lcm_msgs.mbot_balbot_feedback_t import mbot_balbot_feedback_t

# Make both layouts work (utils/ or local files)
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))
try:
    from utils.DataLogger import dataLogger  # type: ignore
    from utils.ps4_controller_api import PS4InputHandler  # type: ignore
except Exception:
    from DataLogger import dataLogger  # type: ignore
    from ps4_controller_api import PS4InputHandler  # type: ignore

# =============================================================================
# SYSTEM CONSTANTS
# =============================================================================

FREQ = 200           # Main loop frequency [Hz]
DT = 1 / FREQ

PWM_MAX = 1.0
PWM_MIN = -1.0

N_GEARBOX = 70
N_ENC = 64
R_W = 0.048  # Wheel radius [m]
R_K = 0.121  # Ball radius [m]

THETA_MAX = np.radians(10.0)  # Safety limit for lean [rad]
IMU_DEADZONE = np.radians(0.3)  # Smaller deadzone for better state estimation

# Physical parameters (approximate; can be refined via system ID)
M_BALL = 0.6  # Ball mass [kg]
M_BOT = 1.5   # Robot body mass [kg]
J_BALL = (2/5) * M_BALL * R_K**2  # Ball inertia (solid sphere)
J_BOT = 0.02  # Robot body inertia about pitch/roll axis [kg·m²]
G = 9.81      # Gravity [m/s²]
H = 0.15      # Center of mass height above ball contact [m]
B = 0.05      # Viscous damping coefficient [N·m·s/rad]

# =============================================================================
# GLOBALS FOR LCM
# =============================================================================

listening = False
msg = mbot_balbot_feedback_t()
last_time = 0
last_seen = {"MBOT_BALBOT_FEEDBACK": 0}


# =============================================================================
# LCM CALLBACK AND LISTENER
# =============================================================================

def feedback_handler(channel, data):
    global msg, last_seen, last_time
    last_time = time.time()
    last_seen[channel] = time.time()
    msg = mbot_balbot_feedback_t.decode(data)


def lcm_listener(lc):
    global listening, last_time, last_seen
    while listening:
        try:
            lc.handle_timeout(100)
            if time.time() - last_time > 2.0:
                print("WARNING: LCM Publisher seems inactive...")
            elif time.time() - last_seen["MBOT_BALBOT_FEEDBACK"] > 2.0:
                print("WARNING: MBOT_BALBOT_FEEDBACK node seems inactive...")
        except Exception as e:
            print(f"ERROR: LCM listening error: {e}")
            break


# =============================================================================
# UTILS
# =============================================================================

def calc_enc2rad(ticks):
    return ticks / (N_GEARBOX * N_ENC) * 2 * np.pi


def calc_kinematic_conv(psi1, psi2, psi3):
    phix = (R_W / R_K) * np.sqrt(2/3) * (psi2 - psi3)
    phiy = (R_W / R_K) * np.sqrt(2)/3 * (-2*psi1 + psi2 + psi3)
    phiz = (R_W / R_K) * np.sqrt(2)/3 * (psi1 + psi2 + psi3)
    return phix, phiy, phiz


def calc_torque_conv(Tx, Ty, Tz):
    u1 = (1/3) * (Tz - (1/np.cos(np.pi/4)) * (2*Ty))
    u2 = (1/3) * (Tz + (1/np.cos(np.pi/4)) * (-np.sqrt(3)*Tx + Ty))
    u3 = (1/3) * (Tz + (1/np.cos(np.pi/4)) * (np.sqrt(3)*Tx + Ty))
    return u1, u2, u3


def func_clip(x, lo, hi):
    if x > hi:
        return hi
    if x < lo:
        return lo
    return x


def apply_deadzone(x, dz):
    return 0.0 if abs(x) < dz else x


# =============================================================================
# LINEARIZED DYNAMICS FOR LQR
# =============================================================================

def get_linearized_dynamics(dt):
    """
    Compute linearized continuous-time dynamics A, B for balancing robot.
    
    Simplified model: 
    - State: x = [θx, θy, θ̇x, θ̇y, φx, φy, φ̇x, φ̇y]ᵀ (8 states)
    - Control: u = [Tx, Ty]ᵀ (2 inputs)
    - Dynamics linearized around upright equilibrium (θ=0, φ=0)
    
    Using inverted pendulum approximation:
    θ̈ ≈ (M_BOT*g*H/J_eff)*θ - (B/J_eff)*θ̇ + (1/J_eff)*T
    φ̈ ≈ -θ̈  (ball motion coupled to body tilt)
    
    Returns:
        A: 8×8 state matrix (continuous-time)
        B: 8×2 input matrix (continuous-time)
        A_d: 8×8 discrete-time state matrix
        B_d: 8×2 discrete-time input matrix
    """
    # Effective inertia
    J_eff = J_BOT + M_BOT * H**2 + J_BALL
    
    # Continuous-time dynamics
    A = np.zeros((8, 8))
    B = np.zeros((8, 2))
    
    # X-axis dynamics (θx, θ̇x, φx, φ̇x)
    # θ̇x = θ̇x
    A[0, 2] = 1.0
    # θ̈x = (M*g*H/J)*θx - (B/J)*θ̇x + (1/J)*Tx
    A[2, 0] = (M_BOT * G * H) / J_eff
    A[2, 2] = -B / J_eff
    B[2, 0] = 1.0 / J_eff
    # φ̇x = φ̇x
    A[4, 6] = 1.0
    # φ̈x = -θ̈x (simplified coupling)
    A[6, 0] = -(M_BOT * G * H) / J_eff
    A[6, 2] = B / J_eff
    B[6, 0] = -1.0 / J_eff
    
    # Y-axis dynamics (θy, θ̇y, φy, φ̇y) - identical structure
    A[1, 3] = 1.0
    A[3, 1] = (M_BOT * G * H) / J_eff
    A[3, 3] = -B / J_eff
    B[3, 1] = 1.0 / J_eff
    A[5, 7] = 1.0
    A[7, 1] = -(M_BOT * G * H) / J_eff
    A[7, 3] = B / J_eff
    B[7, 1] = -1.0 / J_eff
    
    # Discretize using matrix exponential (exact for linear systems)
    # x[k+1] = A_d*x[k] + B_d*u[k]
    n = A.shape[0]
    m = B.shape[1]
    # Augmented matrix for discretization
    M = np.zeros((n+m, n+m))
    M[:n, :n] = A * dt
    M[:n, n:] = B * dt
    M_exp = linalg.expm(M)
    A_d = M_exp[:n, :n]
    B_d = M_exp[:n, n:]
    
    return A, B, A_d, B_d


# =============================================================================
# LQR CONTROLLER
# =============================================================================

class LQRController:
    """
    Linear Quadratic Regulator for optimal state feedback.
    
    Computes control law u = -K*x that minimizes:
        J = Σ (xᵀQx + uᵀRu)
    
    Where:
    - Q: State cost matrix (penalizes deviations from upright/stationary)
    - R: Control cost matrix (penalizes motor effort)
    - K: Optimal feedback gain matrix
    """
    
    def __init__(self, A_d, B_d, Q, R):
        """
        Args:
            A_d: Discrete-time state matrix (n×n)
            B_d: Discrete-time input matrix (n×m)
            Q: State cost matrix (n×n), positive semi-definite
            R: Control cost matrix (m×m), positive definite
        """
        self.A_d = A_d
        self.B_d = B_d
        self.Q = Q
        self.R = R
        
        # Solve discrete-time algebraic Riccati equation (DARE)
        # P = AᵀPA - AᵀPB(R + BᵀPB)⁻¹BᵀPA + Q
        try:
            P = linalg.solve_discrete_are(A_d, B_d, Q, R)
            # Compute optimal gain: K = (R + BᵀPB)⁻¹BᵀPA
            self.K = linalg.solve(R + B_d.T @ P @ B_d, B_d.T @ P @ A_d)
            print(f"✓ LQR gains computed successfully")
            print(f"  K shape: {self.K.shape}")
            print(f"  K =\n{self.K}")
        except Exception as e:
            print(f"ERROR: LQR gain computation failed: {e}")
            # Fallback to zero gains (open-loop)
            self.K = np.zeros((B_d.shape[1], A_d.shape[0]))
    
    def control(self, x_state):
        """
        Compute control input for given state.
        
        Args:
            x_state: Current state vector (8×1)
            
        Returns:
            u: Control input (2×1) = [Tx, Ty]ᵀ
        """
        u = -self.K @ x_state
        return u


# =============================================================================
# EXTENDED KALMAN FILTER
# =============================================================================

class ExtendedKalmanFilter:
    """
    Extended Kalman Filter for state estimation.
    
    Fuses noisy measurements (IMU angles, encoder positions/velocities) to
    estimate full state with reduced noise.
    
    State: x = [θx, θy, θ̇x, θ̇y, φx, φy, φ̇x, φ̇y]ᵀ
    Measurements: z = [θx_imu, θy_imu, φx_enc, φy_enc]ᵀ
    
    Process model: x[k+1] = A*x[k] + B*u[k] + w  (w ~ N(0, Q_proc))
    Measurement model: z[k] = H*x[k] + v  (v ~ N(0, R_meas))
    """
    
    def __init__(self, A_d, B_d, dt):
        """
        Args:
            A_d: Discrete-time state matrix (8×8)
            B_d: Discrete-time input matrix (8×2)
            dt: Sampling period [s]
        """
        self.A = A_d
        self.B = B_d
        self.dt = dt
        
        # State dimension
        self.n = 8
        
        # Measurement matrix H: we measure [θx, θy, φx, φy]
        # z = [θx, θy, φx, φy]ᵀ = H*x
        self.H = np.array([
            [1, 0, 0, 0, 0, 0, 0, 0],  # θx
            [0, 1, 0, 0, 0, 0, 0, 0],  # θy
            [0, 0, 0, 0, 1, 0, 0, 0],  # φx
            [0, 0, 0, 0, 0, 1, 0, 0],  # φy
        ])
        
        # Process noise covariance Q (tune these)
        # Higher values = trust model less, trust measurements more
        q_angle = 1e-4       # Process noise for angles
        q_vel = 1e-3         # Process noise for velocities
        q_pos = 1e-4         # Process noise for positions
        q_pos_vel = 1e-3     # Process noise for position velocities
        self.Q_proc = np.diag([q_angle, q_angle, q_vel, q_vel, 
                               q_pos, q_pos, q_pos_vel, q_pos_vel])
        
        # Measurement noise covariance R (tune these)
        # Based on sensor characteristics
        r_imu = np.radians(0.5)**2    # IMU noise variance [rad²]
        r_enc = np.radians(0.2)**2    # Encoder odometry noise [rad²]
        self.R_meas = np.diag([r_imu, r_imu, r_enc, r_enc])
        
        # Initial state estimate and covariance
        self.x_hat = np.zeros((self.n, 1))
        self.P = np.eye(self.n) * 1.0  # Initial uncertainty
        
        print("✓ EKF initialized")
    
    def predict(self, u):
        """
        Prediction step: propagate state estimate using dynamics.
        
        Args:
            u: Control input (2×1)
        """
        # State prediction: x̂[k|k-1] = A*x̂[k-1|k-1] + B*u[k-1]
        self.x_hat = self.A @ self.x_hat + self.B @ u.reshape(-1, 1)
        
        # Covariance prediction: P[k|k-1] = A*P[k-1|k-1]*Aᵀ + Q
        self.P = self.A @ self.P @ self.A.T + self.Q_proc
    
    def update(self, z_meas):
        """
        Update step: correct state estimate using measurements.
        
        Args:
            z_meas: Measurement vector (4×1) = [θx, θy, φx, φy]ᵀ
        """
        z_meas = z_meas.reshape(-1, 1)
        
        # Innovation: y = z - H*x̂[k|k-1]
        y = z_meas - self.H @ self.x_hat
        
        # Innovation covariance: S = H*P[k|k-1]*Hᵀ + R
        S = self.H @ self.P @ self.H.T + self.R_meas
        
        # Kalman gain: K = P[k|k-1]*Hᵀ*S⁻¹
        K = self.P @ self.H.T @ linalg.inv(S)
        
        # State update: x̂[k|k] = x̂[k|k-1] + K*y
        self.x_hat = self.x_hat + K @ y
        
        # Covariance update: P[k|k] = (I - K*H)*P[k|k-1]
        I = np.eye(self.n)
        self.P = (I - K @ self.H) @ self.P
    
    def get_state(self):
        """
        Get current state estimate.
        
        Returns:
            x_hat: State estimate (8×1)
        """
        return self.x_hat.flatten()


# =============================================================================
# MAIN
# =============================================================================

def main():
    # Data logging
    trial_num = int(input("Test Number? "))
    filename = f"ballbot_control_{trial_num}.txt"
    dl = dataLogger(filename)
    print(f"Data will be saved to: {filename}")

    # LCM setup
    global listening, msg
    lc = lcm.LCM("udpm://239.255.76.67:7667?ttl=0")
    subscription = lc.subscribe("MBOT_BALBOT_FEEDBACK", feedback_handler)
    listening = True
    listener_thread = threading.Thread(target=lcm_listener, args=(lc,), daemon=True)
    listener_thread.start()
    print("✓ LCM listener started")

    # Controller input (R1 to reset IMU)
    controller = PS4InputHandler(interface="/dev/input/js0", connecting_using_ds4drv=False)
    controller_thread = threading.Thread(target=controller.listen, args=(10,))
    controller_thread.daemon = True
    controller_thread.start()
    print("✓ PS4 Controller initialized")

    # Get linearized dynamics
    print("\n" + "="*80)
    print("COMPUTING LQR GAINS")
    print("="*80)
    A, B, A_d, B_d = get_linearized_dynamics(DT)
    print(f"✓ Linearized dynamics computed (A: {A.shape}, B: {B.shape})")
    
    # Design LQR cost matrices
    # Q: State cost (penalize deviations)
    # Diagonal elements: [θx, θy, θ̇x, θ̇y, φx, φy, φ̇x, φ̇y]
    # Higher weight = tighter regulation of that state
    Q = np.diag([
        100.0,  # θx: pitch angle (critical for balance)
        100.0,  # θy: roll angle (critical for balance)
        10.0,   # θ̇x: pitch rate
        10.0,   # θ̇y: roll rate
        1.0,    # φx: ball position X (low weight, allow drift)
        1.0,    # φy: ball position Y (low weight, allow drift)
        0.1,    # φ̇x: ball velocity X
        0.1,    # φ̇y: ball velocity Y
    ])
    
    # R: Control cost (penalize motor effort)
    # Higher weight = less aggressive control
    R = np.diag([
        1.0,    # Tx: X-axis torque
        1.0,    # Ty: Y-axis torque
    ])
    
    # Compute LQR controller
    lqr = LQRController(A_d, B_d, Q, R)
    
    # Initialize EKF
    ekf = ExtendedKalmanFilter(A_d, B_d, DT)
    
    print("\nStarting control loop in 0.5 seconds...")
    time.sleep(0.5)

    # Data header
    data_header = [
        "i", "t_now",
        "Tx", "Ty",
        "u1", "u2", "u3",
        "theta_x_raw", "theta_y_raw",
        "theta_x_est", "theta_y_est",
        "dtheta_x_est", "dtheta_y_est",
        "phi_x_raw", "phi_y_raw",
        "phi_x_est", "phi_y_est",
        "dphi_x_est", "dphi_y_est",
        "x", "y",
    ]
    dl.appendData([" ".join(data_header)])

    # Command message
    command = mbot_motor_pwm_t()

    # Initial references
    enc_pos_1_start = msg.enc_ticks[0]
    enc_pos_2_start = msg.enc_ticks[1]
    enc_pos_3_start = msg.enc_ticks[2]

    theta_x_0 = msg.imu_angles_rpy[0]
    theta_y_0 = msg.imu_angles_rpy[1]
    theta_z_0 = msg.imu_angles_rpy[2]

    # Loop vars
    i = 0
    t_start = time.time()
    u_prev = np.zeros(2)  # Previous control input for EKF prediction

    print("\n" + "="*80)
    print("CONTROL LOOP ACTIVE - LQR+EKF BALANCING")
    print("="*80)
    print("Press R1 to reset IMU reference")
    print("Press Ctrl+C to stop")
    print("="*80 + "\n")

    try:
        while True:
            time.sleep(DT)
            t_now = time.time() - t_start
            i += 1

            # Read sensors
            theta_x_raw = msg.imu_angles_rpy[0] - theta_x_0
            theta_y_raw = msg.imu_angles_rpy[1] - theta_y_0
            theta_z_raw = msg.imu_angles_rpy[2] - theta_z_0

            # Apply light deadzone
            theta_x_meas = apply_deadzone(theta_x_raw, IMU_DEADZONE)
            theta_y_meas = apply_deadzone(theta_y_raw, IMU_DEADZONE)

            # Encoders
            enc_pos_1 = msg.enc_ticks[0] - enc_pos_1_start
            enc_pos_2 = msg.enc_ticks[1] - enc_pos_2_start
            enc_pos_3 = msg.enc_ticks[2] - enc_pos_3_start

            psi_1 = calc_enc2rad(enc_pos_1)
            psi_2 = calc_enc2rad(enc_pos_2)
            psi_3 = calc_enc2rad(enc_pos_3)

            phi_x_raw, phi_y_raw, phi_z = calc_kinematic_conv(psi_1, psi_2, psi_3)
            x = phi_x_raw * R_K
            y = phi_y_raw * R_K

            # Inputs
            bt = controller.get_signals()
            shoulder_R1 = bt["shoulder_R1"]
            if shoulder_R1 == 1:
                theta_x_0 = msg.imu_angles_rpy[0]
                theta_y_0 = msg.imu_angles_rpy[1]
                theta_z_0 = msg.imu_angles_rpy[2]
                # Reset EKF state
                ekf.x_hat = np.zeros((8, 1))
                ekf.P = np.eye(8) * 1.0
                print("\n>>> IMU REFERENCE RESET + EKF RESET <<<\n")

            # EKF prediction step
            ekf.predict(u_prev)

            # EKF update step with measurements
            z_meas = np.array([theta_x_meas, theta_y_meas, phi_x_raw, phi_y_raw])
            ekf.update(z_meas)

            # Get estimated state
            x_state = ekf.get_state()
            theta_x_est = x_state[0]
            theta_y_est = x_state[1]
            dtheta_x_est = x_state[2]
            dtheta_y_est = x_state[3]
            phi_x_est = x_state[4]
            phi_y_est = x_state[5]
            dphi_x_est = x_state[6]
            dphi_y_est = x_state[7]

            # Safety check
            if abs(theta_x_est) > THETA_MAX or abs(theta_y_est) > THETA_MAX:
                print(f"\n!!! SAFETY LIMIT EXCEEDED: θx={np.degrees(theta_x_est):.1f}°, θy={np.degrees(theta_y_est):.1f}° !!!")
                print("Stopping motors...\n")
                Tx = Ty = 0.0
            else:
                # LQR control
                u = lqr.control(x_state)
                Tx = float(u[0])
                Ty = float(u[1])

            # Store control for next iteration's EKF prediction
            u_prev = np.array([Tx, Ty])

            # Convert to motor PWMs (no yaw)
            u1, u2, u3 = calc_torque_conv(Tx, Ty, 0.0)
            u1 = func_clip(u1, PWM_MIN, PWM_MAX)
            u2 = func_clip(u2, PWM_MIN, PWM_MAX)
            u3 = func_clip(u3, PWM_MIN, PWM_MAX)

            # Publish
            command.utime = int(time.time() * 1e6)
            command.pwm[0] = u1
            command.pwm[1] = u2
            command.pwm[2] = u3
            lc.publish("MBOT_MOTOR_PWM_CMD", command.encode())

            # Log
            dl.appendData([
                i, t_now,
                Tx, Ty,
                u1, u2, u3,
                theta_x_raw, theta_y_raw,
                theta_x_est, theta_y_est,
                dtheta_x_est, dtheta_y_est,
                phi_x_raw, phi_y_raw,
                phi_x_est, phi_y_est,
                dphi_x_est, dphi_y_est,
                x, y,
            ])

            # Console every 10 cycles
            if i % 10 == 0:
                print(
                    f"t={t_now:.2f}s | T=[{Tx:.2f},{Ty:.2f}] | u=[{u1:.2f},{u2:.2f},{u3:.2f}] | "
                    f"θ_est=[{np.degrees(theta_x_est):.1f}°, {np.degrees(theta_y_est):.1f}°] | "
                    f"θ̇_est=[{np.degrees(dtheta_x_est):.1f}°/s, {np.degrees(dtheta_y_est):.1f}°/s]"
                )

    except KeyboardInterrupt:
        print("\n\n=== EMERGENCY STOP ===")
        command = mbot_motor_pwm_t()
        command.utime = int(time.time() * 1e6)
        command.pwm[0] = 0.0
        command.pwm[1] = 0.0
        command.pwm[2] = 0.0
        lc.publish("MBOT_MOTOR_PWM_CMD", command.encode())
    finally:
        print("\n=== SHUTDOWN ===")
        print(f"→ Saving data to {filename}...")
        dl.writeOut()
        global listening
        listening = False
        time.sleep(0.2)
        try:
            controller.on_options_press()
        except Exception:
            pass
        # Final motor off
        command = mbot_motor_pwm_t()
        command.utime = int(time.time() * 1e6)
        command.pwm[0] = 0.0
        command.pwm[1] = 0.0
        command.pwm[2] = 0.0
        lc.publish("MBOT_MOTOR_PWM_CMD", command.encode())
        print("✓ Motors confirmed off")
        print("✓ Data saved")


if __name__ == "__main__":
    """
    LQR+EKF Ball-Bot Controller
    
    TUNING GUIDE:
    
    1. Q Matrix (State Cost):
       - Increase θx/θy weights → tighter angle regulation (more aggressive)
       - Increase φx/φy weights → reduce position drift (if needed)
       - Increase velocity weights → reduce oscillations
       
    2. R Matrix (Control Cost):
       - Decrease R → more aggressive control (may oscillate)
       - Increase R → smoother, less aggressive control
       
    3. EKF Tuning:
       - Q_proc: Process noise (model uncertainty)
         Higher → trust measurements more
       - R_meas: Measurement noise (sensor noise)
         Higher → trust model more
       
    4. Physical Parameters:
       - M_BALL, M_BOT, J_BOT, H: Measured from robot
       - Can be refined via system identification
       
    TROUBLESHOOTING:
    
    - Falls immediately: Increase Q weights for θx/θy or decrease R
    - Oscillates: Decrease Q weights or increase R, check damping B
    - Drifts in position: Increase Q weights for φx/φy
    - Noisy control: Increase R_meas in EKF or increase R in LQR
    - Poor state estimates: Tune EKF Q_proc and R_meas
    """
    
    main()
